#!/usr/bin/env bash
# Re-run only the batches that had any FAILED proteins.
#
# How: deletes the .done sentinel for every batch whose .failed file is
# non-empty, then re-invokes snakemake. The idempotent skip inside
# run_batch.sh means proteins already with both a3m+hhm are no-ops; only
# the previously-failed proteins actually get re-processed (and now with
# the tier-aware longer timeout).
#
# Safe to run repeatedly. Reads only state on disk; no destructive ops
# outside of (a) deleting .done sentinels (cheap, regenerated by snakemake)
# and (b) deleting the pack outputs so the DB rebuilds.
#
# Usage:
#   bash workflow/scripts/retry_failed_batches.sh           # plan + run
#   bash workflow/scripts/retry_failed_batches.sh --plan    # print only
#
# Run AFTER the main production run has finished cleanly.

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$ROOT"

PLAN_ONLY=0
[ "${1:-}" = "--plan" ] && PLAN_ONLY=1

echo "[$(date -Is)] scanning data/batches/*.failed ..."
mapfile -t failed_batches < <(
  for f in data/batches/*.failed; do
    [ -s "$f" ] && basename "$f" .failed
  done | sort -u
)

n=${#failed_batches[@]}
if [ "$n" -eq 0 ]; then
  echo "no batches with failures — nothing to retry."
  exit 0
fi

echo "[$(date -Is)] $n batches have failures:"
for bid in "${failed_batches[@]:0:5}"; do
  n_fail=$(wc -l < "data/batches/${bid}.failed")
  echo "  $bid  ($n_fail failed proteins)"
done
[ "$n" -gt 5 ] && echo "  ... + $((n-5)) more"

if [ "$PLAN_ONLY" -eq 1 ]; then
  echo "--plan only; not modifying anything."
  exit 0
fi

echo "[$(date -Is)] removing .done sentinels for those batches ..."
for bid in "${failed_batches[@]}"; do
  rm -f "data/batches/${bid}.done"
done

echo "[$(date -Is)] removing pack outputs so the DB rebuilds with the recovered proteins ..."
rm -f data/db/marchantia_v7.1_*
rm -f results/validation/marchantia_v7.1.integrity.ok
rm -f results/validation/marchantia_v7.1.summary.tsv
rm -f results/run_report.md results/failed_proteins.tsv

echo "[$(date -Is)] re-running snakemake with tier-aware timeout (now in config.yaml) ..."
nohup snakemake --profile profiles/slurm --config mode=production \
    > logs/retry_run.log 2>&1 &
echo "RETRY_PID=$!"
echo "$!" > logs/retry_run.pid
echo
echo "tail -f logs/retry_run.log    to watch."
